import { StyleSheet } from 'react-native';
import { useTheme } from '@react-navigation/native';
import { useDeviceDimensions } from '@hooks/useDeviceDimensions';

const useStyles = () => {
  const { colors } = useTheme();
  const { moderateWidth, moderateHeight } = useDeviceDimensions();

  return StyleSheet.create({
    header: {
      minHeight: moderateHeight(6.3),
      paddingVertical: moderateHeight(1),
      paddingHorizontal: moderateWidth(4),
      backgroundColor: colors.primary,
    },
    headerTitle: {
      color: colors.white,
      fontSize: moderateHeight(2.1),
      textTransform: 'none',
    },
    content: {
      paddingHorizontal: moderateWidth(4.7),
      paddingTop: moderateHeight(1.4),
      paddingBottom: moderateHeight(3.4),
      backgroundColor: colors.background,
    },
    fullHeightContent: {
      flex: 1,
    },
    form: {
      flexGrow: 1,
      paddingBottom: moderateHeight(2),
      justifyContent: 'flex-start',
    },
    summaryCard: {
      minHeight: moderateHeight(8.6),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: moderateHeight(1.45),
      paddingVertical: moderateHeight(1.35),
      paddingHorizontal: moderateWidth(3.6),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    summaryIcon: {
      width: moderateWidth(12),
      height: moderateWidth(12),
      borderRadius: moderateWidth(6),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    summaryIconGlyph: {
      width: moderateWidth(5.6),
      height: moderateWidth(5.6),
      color: colors.primary,
    },
    summaryTextBlock: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3.2),
    },
    summaryTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.75),
      lineHeight: moderateHeight(2.25),
    },
    summaryText: {
      color: colors.gray,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.9),
      marginTop: moderateHeight(0.25),
    },
    sectionCard: {
      paddingTop: moderateHeight(1.6),
      paddingBottom: moderateHeight(0.4),
      paddingHorizontal: moderateWidth(3.4),
      marginBottom: moderateHeight(1.45),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    sectionHeader: {
      minHeight: moderateHeight(2.4),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: moderateHeight(1.2),
    },
    sectionTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.55),
    },
    sectionMeta: {
      color: colors.primary,
      fontSize: moderateHeight(1.2),
    },
    inputWrapper: {
      height: moderateHeight(5.7),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      borderRadius: moderateWidth(2),
      paddingLeft: moderateWidth(3.2),
      paddingRight: moderateWidth(2.8),
      backgroundColor: colors.primarySurface,
    },
    inputText: {
      color: colors.text,
      fontSize: moderateHeight(1.48),
      height: moderateHeight(5.4),
    },
    selectText: {
      color: colors.text,
      fontSize: moderateHeight(1.48),
      lineHeight: moderateHeight(2.1),
    },
    dropdownWrapper: {
      flex: 0,
      marginTop: 0,
      marginBottom: moderateHeight(2),
    },
    placeholder: {
      color: colors.gray,
    },
    iconBubble: {
      width: moderateWidth(7.2),
      height: moderateWidth(7.2),
      borderRadius: moderateWidth(3.6),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    iconBubblePressed: {
      opacity: 0.72,
    },
    fieldIcon: {
      width: moderateWidth(4),
      height: moderateWidth(4),
      color: colors.primary,
    },
    dropdownIcon: {
      width: moderateWidth(4.8),
      height: moderateWidth(4.8),
      color: colors.primary,
    },
    confirmButton: {
      height: moderateHeight(5.9),
      borderRadius: moderateWidth(2.4),
      marginTop: moderateHeight(1),
      marginBottom: moderateHeight(1),
      shadowColor: colors.primaryDark,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.16,
      shadowRadius: 9,
      elevation: 3,
    },
    confirmButtonText: {
      color: colors.white,
      fontSize: moderateHeight(1.7),
    },
    listContainer: {
      flex: 1,
      position: 'relative',
    },
    listContent: {
      flexGrow: 1,
      paddingBottom: moderateHeight(10),
    },
    visitorCard: {
      minHeight: moderateHeight(10.4),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: moderateHeight(1.3),
      paddingVertical: moderateHeight(1.35),
      paddingHorizontal: moderateWidth(3.4),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      marginHorizontal: moderateWidth(0.2),
    },
    visitorCardPressed: {
      opacity: 0.76,
    },
    visitorAvatar: {
      width: moderateWidth(11),
      height: moderateWidth(11),
      borderRadius: moderateWidth(5.5),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    visitorAvatarIcon: {
      width: moderateWidth(5),
      height: moderateWidth(5),
      color: colors.primary,
    },
    visitorCardBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3),
    },
    visitorName: {
      color: colors.secondary,
      fontSize: moderateHeight(1.72),
      lineHeight: moderateHeight(2.25),
    },
    visitorCompany: {
      color: colors.gray,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.9),
      marginTop: moderateHeight(0.3),
    },
    visitorMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: moderateHeight(0.7),
    },
    metaIcon: {
      width: moderateWidth(3.6),
      height: moderateWidth(3.6),
      color: colors.primary,
    },
    visitorMetaText: {
      flex: 1,
      color: colors.text,
      fontSize: moderateHeight(1.32),
      lineHeight: moderateHeight(1.85),
      marginLeft: moderateWidth(1.4),
    },
    chevron: {
      width: moderateWidth(4.8),
      height: moderateWidth(4.8),
      color: colors.gray,
    },
    addButton: {
      position: 'absolute',
      right: moderateWidth(1.2),
      bottom: moderateHeight(0),
      width: moderateWidth(14),
      height: moderateWidth(14),
      borderRadius: moderateWidth(7),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      elevation: 5,
      shadowRadius: 8,
      shadowOpacity: 0.18,
      shadowColor: colors.primaryDark,
      shadowOffset: { width: 0, height: 4 },
    },
    addButtonPressed: {
      opacity: 0.78,
    },
    addIcon: {
      width: moderateWidth(7),
      height: moderateWidth(7),
      color: colors.white,
    },
    loaderContainer: {
      flex: 1,
      minHeight: moderateHeight(45),
      alignItems: 'center',
      justifyContent: 'center',
    },
    loaderIcon: {
      color: colors.primary,
    },
    paginationLoader: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: moderateHeight(1.8),
    },
    refreshControl: {
      color: colors.primary,
    },
    emptyState: {
      flex: 1,
      minHeight: moderateHeight(45),
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(8),
    },
    emptyTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.9),
      lineHeight: moderateHeight(2.45),
    },
    emptyText: {
      color: colors.gray,
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(2.1),
      marginTop: moderateHeight(0.6),
    },
    detailContent: {
      paddingBottom: moderateHeight(3),
    },
    detailHero: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: moderateHeight(1.45),
      paddingVertical: moderateHeight(1.7),
      paddingHorizontal: moderateWidth(3.6),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    detailHeroIcon: {
      width: moderateWidth(13),
      height: moderateWidth(13),
      borderRadius: moderateWidth(6.5),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    detailHeroGlyph: {
      width: moderateWidth(6),
      height: moderateWidth(6),
      color: colors.primary,
    },
    detailHeroBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3.2),
    },
    detailName: {
      color: colors.secondary,
      fontSize: moderateHeight(1.9),
      lineHeight: moderateHeight(2.55),
    },
    detailCompany: {
      color: colors.gray,
      fontSize: moderateHeight(1.4),
      lineHeight: moderateHeight(2),
      marginTop: moderateHeight(0.3),
    },
    statusPill: {
      alignSelf: 'flex-start',
      marginTop: moderateHeight(0.9),
      paddingVertical: moderateHeight(0.45),
      paddingHorizontal: moderateWidth(2.4),
      borderRadius: moderateWidth(4),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    statusText: {
      color: colors.primary,
      fontSize: moderateHeight(1.2),
      textTransform: 'capitalize',
    },
    detailCard: {
      marginBottom: moderateHeight(1.45),
      paddingTop: moderateHeight(1.4),
      paddingHorizontal: moderateWidth(3.4),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    detailSectionTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.55),
      lineHeight: moderateHeight(2.15),
      marginBottom: moderateHeight(0.8),
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: moderateHeight(1),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    detailRowIcon: {
      width: moderateWidth(8),
      height: moderateWidth(8),
      borderRadius: moderateWidth(4),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      marginRight: moderateWidth(2.5),
    },
    detailIcon: {
      width: moderateWidth(4),
      height: moderateWidth(4),
      color: colors.primary,
    },
    detailRowBody: {
      flex: 1,
      minWidth: 0,
    },
    detailLabel: {
      color: colors.gray,
      fontSize: moderateHeight(1.2),
      lineHeight: moderateHeight(1.7),
    },
    detailValue: {
      color: colors.text,
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(2.05),
      marginTop: moderateHeight(0.2),
    },
  });
};

export default useStyles;
