import { StyleSheet } from 'react-native';
import { useTheme } from '@react-navigation/native';
import { useDeviceDimensions } from '@hooks/useDeviceDimensions';

const useStyles = () => {
  const { colors } = useTheme();
  const { moderateWidth, moderateHeight } = useDeviceDimensions();

  return StyleSheet.create({
    content: {
      paddingHorizontal: 0,
      backgroundColor: colors.background,
    },
    container: {
      flexGrow: 1,
      paddingHorizontal: moderateWidth(4.7),
      paddingTop: moderateHeight(1.2),
      paddingBottom: moderateHeight(3),
      backgroundColor: colors.background,
    },
    avatarCard: {
      minHeight: moderateHeight(12),
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: moderateHeight(1.4),
      paddingHorizontal: moderateWidth(3.6),
      borderRadius: moderateWidth(2.6),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
    },
    avatar: {
      width: moderateWidth(17),
      height: moderateWidth(17),
      borderRadius: moderateWidth(8.5),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    avatarBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3.2),
    },
    avatarName: {
      color: colors.secondary,
      fontSize: moderateHeight(1.85),
      lineHeight: moderateHeight(2.4),
    },
    avatarMeta: {
      color: colors.gray,
      fontSize: moderateHeight(1.33),
      lineHeight: moderateHeight(1.85),
      marginTop: moderateHeight(0.25),
    },
    avatarBadge: {
      alignSelf: 'flex-start',
      minHeight: moderateHeight(3.25),
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: moderateWidth(2.2),
      borderRadius: moderateWidth(5),
      marginTop: moderateHeight(0.85),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    avatarBadgeIcon: {
      width: moderateWidth(3.5),
      height: moderateWidth(3.5),
      color: colors.primary,
    },
    avatarBadgeText: {
      color: colors.primary,
      fontSize: moderateHeight(1.2),
      lineHeight: moderateHeight(1.7),
      marginLeft: moderateWidth(1),
    },
    stepTabs: {
      flexDirection: 'row',
      marginTop: moderateHeight(1.25),
      padding: moderateWidth(0.8),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    stepTab: {
      flex: 1,
      minHeight: moderateHeight(4.35),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(1.8),
      paddingHorizontal: moderateWidth(1),
    },
    stepTabActive: {
      backgroundColor: colors.primary,
    },
    stepTabText: {
      color: colors.gray,
      fontSize: moderateHeight(1.25),
    },
    stepTabTextActive: {
      color: colors.white,
    },
    sectionCard: {
      marginTop: moderateHeight(1.25),
      paddingTop: moderateHeight(1.45),
      paddingHorizontal: moderateWidth(3.4),
      paddingBottom: moderateHeight(0.6),
      borderRadius: moderateWidth(2.6),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
    },
    sectionHeader: {
      minHeight: moderateHeight(5.6),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: moderateHeight(1.25),
      paddingBottom: moderateHeight(1.25),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    sectionHeaderIcon: {
      width: moderateWidth(10),
      height: moderateWidth(10),
      borderRadius: moderateWidth(5),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    sectionHeaderGlyph: {
      width: moderateWidth(5),
      height: moderateWidth(5),
      color: colors.white,
    },
    sectionHeaderBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(2.7),
    },
    sectionTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.65),
      lineHeight: moderateHeight(2.2),
    },
    sectionSubtitle: {
      color: colors.gray,
      fontSize: moderateHeight(1.22),
      lineHeight: moderateHeight(1.7),
      marginTop: moderateHeight(0.2),
    },
    inputWrapper: {
      height: moderateHeight(5.7),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      borderRadius: moderateWidth(2),
      paddingHorizontal: moderateWidth(3),
      backgroundColor: colors.primarySurface,
    },
    inputText: {
      color: colors.text,
      fontSize: moderateHeight(1.45),
      height: moderateHeight(5.4),
    },
    fieldLabel: {
      color: colors.text,
      fontSize: moderateHeight(1.32),
      lineHeight: moderateHeight(1.85),
      marginBottom: moderateHeight(0.7),
    },
    textAreaBlock: {
      marginBottom: moderateHeight(1.2),
    },
    textArea: {
      minHeight: moderateHeight(10.4),
      color: colors.text,
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(2.05),
      paddingTop: moderateHeight(1.2),
      paddingBottom: moderateHeight(1.1),
      paddingHorizontal: moderateWidth(3),
      borderRadius: moderateWidth(2),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    dateWrapper: {
      flex: 0,
      marginTop: 0,
      marginBottom: moderateHeight(0.7),
    },
    dateText: {
      color: colors.text,
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(2.05),
      marginLeft: moderateWidth(2),
    },
    dateIcon: {
      width: moderateWidth(4.2),
      height: moderateWidth(4.2),
      color: colors.primary,
    },
    inlineDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginTop: moderateHeight(0.3),
      marginBottom: moderateHeight(1.4),
    },
    toggleRow: {
      minHeight: moderateHeight(5.6),
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: moderateWidth(3),
      marginBottom: moderateHeight(1.2),
      borderRadius: moderateWidth(2),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    checkbox: {
      width: moderateWidth(5),
      height: moderateWidth(5),
      borderRadius: moderateWidth(1.2),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    checkboxActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    checkboxIcon: {
      width: moderateWidth(3.5),
      height: moderateWidth(3.5),
      color: colors.white,
    },
    toggleText: {
      flex: 1,
      color: colors.secondary,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.9),
      marginLeft: moderateWidth(2.4),
    },
    readonlyItem: {
      minHeight: moderateHeight(6.1),
      justifyContent: 'center',
      paddingVertical: moderateHeight(0.8),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    readonlyLabel: {
      color: colors.gray,
      fontSize: moderateHeight(1.18),
      lineHeight: moderateHeight(1.65),
    },
    readonlyValue: {
      color: colors.secondary,
      fontSize: moderateHeight(1.42),
      lineHeight: moderateHeight(1.95),
      marginTop: moderateHeight(0.2),
    },
    tipCard: {
      minHeight: moderateHeight(6.6),
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: moderateHeight(1.2),
      paddingVertical: moderateHeight(1.1),
      paddingHorizontal: moderateWidth(3.2),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    tipIcon: {
      width: moderateWidth(2.4),
      height: moderateWidth(2.4),
      color: colors.primary,
    },
    tipBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(2.2),
    },
    tipTitle: {
      color: colors.primary,
      fontSize: moderateHeight(1.32),
      lineHeight: moderateHeight(1.85),
    },
    tipText: {
      color: colors.gray,
      fontSize: moderateHeight(1.18),
      lineHeight: moderateHeight(1.65),
      marginTop: moderateHeight(0.15),
    },
    footer: {
      minHeight: moderateHeight(7.8),
      flexDirection: 'row',
      alignItems: 'center',
      columnGap: moderateWidth(2.4),
      paddingTop: moderateHeight(1.2),
      paddingBottom: moderateHeight(1.4),
    },
    footerSpacer: {
      flex: 0.7,
    },
    footerSecondaryButton: {
      flex: 0.75,
      height: moderateHeight(5.8),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(2.2),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    footerPrimaryButton: {
      flex: 1.25,
      height: moderateHeight(5.8),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(2.2),
      backgroundColor: colors.primary,
      elevation: 3,
      shadowColor: colors.primaryDark,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.16,
      shadowRadius: 9,
      paddingHorizontal: moderateWidth(2.2),
    },
    footerDisabledButton: {
      opacity: 0.58,
    },
    footerIcon: {
      width: moderateWidth(4.2),
      height: moderateWidth(4.2),
    },
    footerPrimaryText: {
      color: colors.white,
      fontSize: moderateHeight(1.42),
      lineHeight: moderateHeight(1.9),
      marginHorizontal: moderateWidth(1),
    },
    footerSecondaryText: {
      color: colors.secondary,
      fontSize: moderateHeight(1.42),
      lineHeight: moderateHeight(1.9),
      marginHorizontal: moderateWidth(1),
    },
    controlPressed: {
      opacity: 0.76,
    },
  });
};

export default useStyles;
