import { StyleSheet } from 'react-native';
import { useTheme } from '@react-navigation/native';
import { useDeviceDimensions } from '@hooks/useDeviceDimensions';

const useStyles = () => {
  const { colors } = useTheme();
  const { moderateWidth, moderateHeight } = useDeviceDimensions();

  return StyleSheet.create({
    header: {
      minHeight: moderateHeight(6.3),
      paddingVertical: moderateHeight(1),
      paddingHorizontal: moderateWidth(4),
      backgroundColor: colors.primary,
    },
    headerTitle: {
      color: colors.white,
      fontSize: moderateHeight(2.1),
      textTransform: 'none',
    },
    content: {
      paddingHorizontal: 0,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    tabs: {
      flexDirection: 'row',
      marginTop: moderateHeight(1),
      marginHorizontal: moderateWidth(4.7),
      padding: moderateWidth(0.8),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    tab: {
      flex: 1,
      minHeight: moderateHeight(4.5),
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      borderRadius: moderateWidth(1.8),
    },
    tabText: {
      color: colors.gray,
      fontSize: moderateHeight(1.25),
    },
    activeTab: {
      backgroundColor: colors.primary,
    },
    activeTabText: {
      color: colors.white,
    },
    rosterContainer: {
      flex: 1,
    },
    searchPanel: {
      marginTop: moderateHeight(1.35),
      marginHorizontal: moderateWidth(4.7),
      marginBottom: moderateHeight(0.6),
      padding: moderateWidth(3.2),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    rosterSummary: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: moderateHeight(1.3),
    },
    rosterTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.75),
    },
    rosterCount: {
      color: colors.primary,
      fontSize: moderateHeight(1.32),
    },
    searchBox: {
      height: moderateHeight(5.15),
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      borderRadius: moderateWidth(2),
      paddingHorizontal: moderateWidth(3.2),
      backgroundColor: colors.primarySurface,
    },
    searchInput: {
      flex: 1,
      height: '100%',
      marginLeft: moderateWidth(2),
    },
    searchIcon: {
      width: moderateWidth(4.6),
      height: moderateWidth(4.6),
      color: colors.primary,
    },
    memberList: {
      paddingHorizontal: moderateWidth(4.7),
      paddingTop: moderateHeight(0.8),
      paddingBottom: moderateHeight(3),
      rowGap: moderateHeight(1.25),
    },
    memberCard: {
      minHeight: moderateHeight(10.4),
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: moderateHeight(1.35),
      paddingHorizontal: moderateWidth(3.4),
      borderRadius: moderateWidth(2.3),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    memberCardPressed: {
      opacity: 0.72,
    },
    avatarShell: {
      width: moderateWidth(12),
      height: moderateWidth(12),
      borderRadius: moderateWidth(6),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    avatar: {
      width: moderateWidth(10.4),
      height: moderateWidth(10.4),
      borderRadius: moderateWidth(5.2),
      backgroundColor: colors.background,
    },
    memberInfo: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3.4),
    },
    memberName: {
      color: colors.secondary,
      fontSize: moderateHeight(1.55),
      lineHeight: moderateHeight(2.05),
      textTransform: 'capitalize',
    },
    memberMetaRow: {
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: moderateHeight(0.35),
    },
    memberMetaIcon: {
      width: moderateWidth(3.5),
      height: moderateWidth(3.5),
      color: colors.gray,
    },
    memberMeta: {
      flex: 1,
      color: colors.gray,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.85),
      marginLeft: moderateWidth(1.4),
    },
    memberSpecialtyPill: {
      alignSelf: 'flex-start',
      maxWidth: '100%',
      minHeight: moderateHeight(2.9),
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: moderateHeight(0.65),
      paddingVertical: moderateHeight(0.35),
      paddingHorizontal: moderateWidth(2),
      borderRadius: moderateWidth(5),
      backgroundColor: colors.primarySurface,
    },
    specialtyIcon: {
      width: moderateWidth(3.3),
      height: moderateWidth(3.3),
      color: colors.primary,
    },
    memberSpecialty: {
      flexShrink: 1,
      color: colors.primaryDark,
      fontSize: moderateHeight(1.18),
      lineHeight: moderateHeight(1.55),
      marginLeft: moderateWidth(1.2),
    },
    memberChevron: {
      width: moderateWidth(4.8),
      height: moderateWidth(4.8),
      color: colors.primary,
    },
    formContent: {
      paddingHorizontal: moderateWidth(4.7),
      paddingTop: moderateHeight(2),
      paddingBottom: moderateHeight(3),
    },
    instructions: {
      color: colors.gray,
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(2.05),
      marginHorizontal: moderateWidth(5),
      marginBottom: moderateHeight(2.1),
    },
    formCard: {
      paddingHorizontal: moderateWidth(3.5),
      paddingTop: moderateHeight(2),
      paddingBottom: moderateHeight(1.4),
      marginBottom: moderateHeight(1.8),
      borderRadius: moderateWidth(2.3),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    formTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.5),
      marginBottom: moderateHeight(2),
    },
    fieldRow: {
      flexDirection: 'row',
      columnGap: moderateWidth(2.6),
    },
    input: {
      height: moderateHeight(4.9),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      borderRadius: moderateWidth(2),
      paddingHorizontal: moderateWidth(3.5),
      marginBottom: moderateHeight(1.6),
      backgroundColor: colors.primarySurface,
    },
    inputText: {
      color: colors.text,
      fontSize: moderateHeight(1.45),
      paddingVertical: 0,
      textAlignVertical: 'center',
    },
    placeholder: {
      color: colors.gray,
    },
    countryInput: {
      height: moderateHeight(5.3),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      borderRadius: moderateWidth(2),
      paddingHorizontal: moderateWidth(3.5),
      marginBottom: moderateHeight(2),
      backgroundColor: colors.primarySurface,
    },
    countryText: {
      flex: 1,
      color: colors.text,
      fontSize: moderateHeight(1.45),
    },
    downIcon: {
      width: moderateWidth(4.5),
      height: moderateWidth(4.5),
      color: colors.gray,
    },
    searchButton: {
      height: moderateHeight(5.8),
      borderRadius: moderateWidth(2.3),
    },
    searchButtonText: {
      color: colors.white,
      fontSize: moderateHeight(1.65),
    },
    emptyState: {
      minHeight: moderateHeight(18),
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(6),
      borderRadius: moderateWidth(2.3),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    emptyTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.6),
    },
    emptyText: {
      color: colors.gray,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.9),
      marginTop: moderateHeight(0.45),
    },
  });
};

export default useStyles;
