import { StyleSheet } from 'react-native';
import { useTheme } from '@react-navigation/native';
import { useDeviceDimensions } from '@hooks/useDeviceDimensions';

const useStyles = () => {
  const { colors } = useTheme();
  const { moderateWidth, moderateHeight } = useDeviceDimensions();

  return StyleSheet.create({
    header: {
      minHeight: moderateHeight(6.3),
      paddingVertical: moderateHeight(1),
      paddingHorizontal: moderateWidth(4),
      backgroundColor: colors.primary,
    },
    headerTitle: {
      color: colors.white,
      fontSize: moderateHeight(2.1),
      textTransform: 'none',
    },
    headerIcon: {
      color: colors.white,
    },
    content: {
      paddingHorizontal: 0,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    topControls: {
      zIndex: 5,
      flexDirection: 'row',
      alignItems: 'center',
      paddingTop: moderateHeight(1),
      paddingHorizontal: moderateWidth(4.7),
    },
    tabs: {
      flex: 1,
      flexDirection: 'row',
      padding: moderateWidth(0.8),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    tab: {
      flex: 1,
      minHeight: moderateHeight(4.5),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(1.8),
    },
    activeTab: {
      backgroundColor: colors.primary,
    },
    tabText: {
      color: colors.gray,
      fontSize: moderateHeight(1.35),
    },
    activeTabText: {
      color: colors.white,
    },
    filterButton: {
      width: moderateHeight(5.4),
      height: moderateHeight(5.4),
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: moderateWidth(2),
      borderRadius: moderateWidth(2),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    activeFilterButton: {
      backgroundColor: colors.primary,
    },
    filterButtonPressed: {
      opacity: 0.72,
    },
    filterIcon: {
      width: moderateWidth(5),
      height: moderateWidth(5),
      color: colors.primary,
    },
    activeFilterIcon: {
      color: colors.white,
    },
    filterPopover: {
      position: 'absolute',
      top: moderateHeight(7.1),
      right: moderateWidth(4.7),
      width: moderateWidth(58),
      overflow: 'visible',
      padding: moderateWidth(2.6),
      borderRadius: moderateWidth(2.6),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 8,
      shadowRadius: 10,
      shadowOpacity: 0.18,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 5 },
    },
    filterPopoverArrow: {
      position: 'absolute',
      top: moderateHeight(-0.75),
      right: moderateWidth(4.5),
      width: moderateHeight(1.5),
      height: moderateHeight(1.5),
      transform: [{ rotate: '45deg' }],
      backgroundColor: colors.white,
      borderLeftWidth: StyleSheet.hairlineWidth,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    filterPopoverHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: moderateHeight(1.2),
    },
    filterTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.55),
    },
    clearFilterText: {
      color: colors.primary,
      fontSize: moderateHeight(1.35),
    },
    clearFilterButton: {
      minHeight: moderateHeight(3.2),
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: moderateWidth(2),
      borderRadius: moderateWidth(1.6),
      backgroundColor: colors.primarySurface,
    },
    clearFilterIcon: {
      width: moderateWidth(3.5),
      height: moderateWidth(3.5),
      color: colors.primary,
    },
    filterOptions: {
      rowGap: moderateHeight(1),
    },
    filterOption: {
      minHeight: moderateHeight(5.8),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      borderRadius: moderateWidth(2.2),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      paddingHorizontal: moderateWidth(2.4),
    },
    activeFilterOption: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    filterOptionPressed: {
      opacity: 0.72,
    },
    filterOptionIcon: {
      width: moderateWidth(4.7),
      height: moderateWidth(4.7),
      color: colors.primary,
    },
    filterOptionText: {
      color: colors.secondary,
      textAlign: 'left',
      fontSize: moderateHeight(1.35),
      marginLeft: moderateWidth(1.2),
    },
    activeFilterOptionText: {
      color: colors.white,
    },
    summaryCard: {
      marginTop: moderateHeight(1.35),
      marginHorizontal: moderateWidth(4.7),
      paddingVertical: moderateHeight(1.2),
      paddingHorizontal: moderateWidth(3.6),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    summaryTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.65),
      lineHeight: moderateHeight(2.15),
    },
    summarySubtitle: {
      color: colors.gray,
      fontSize: moderateHeight(1.28),
      lineHeight: moderateHeight(1.8),
      marginTop: moderateHeight(0.2),
    },
    listContent: {
      paddingHorizontal: moderateWidth(4.7),
      paddingTop: moderateHeight(1.25),
      paddingBottom: moderateHeight(13),
      rowGap: moderateHeight(1.1),
    },
    loaderContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loaderIcon: {
      color: colors.primary,
    },
    refreshControl: {
      color: colors.primary,
    },
    paginationLoader: {
      minHeight: moderateHeight(5.6),
      alignItems: 'center',
      justifyContent: 'center',
    },
    slipCard: {
      minHeight: moderateHeight(10.2),
      flexDirection: 'row',
      alignItems: 'center',
      overflow: 'hidden',
      position: 'relative',
      paddingVertical: moderateHeight(1.25),
      paddingHorizontal: moderateWidth(3.2),
      borderRadius: moderateWidth(2.3),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    slipCardPressed: {
      opacity: 0.72,
    },
    highlightBar: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: moderateWidth(1.3),
      backgroundColor: colors.toastSuccess,
    },
    slipIconShell: {
      width: moderateWidth(12),
      height: moderateWidth(12),
      borderRadius: moderateWidth(6),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    highlightedSlipIconShell: {
      backgroundColor: colors.toastSuccess,
      borderColor: colors.toastSuccess,
    },
    slipIcon: {
      width: moderateWidth(5.8),
      height: moderateWidth(5.8),
      color: colors.gray,
    },
    highlightedSlipIcon: {
      color: colors.primary,
    },
    slipBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3.2),
    },
    slipDate: {
      color: colors.gray,
      fontSize: moderateHeight(1.38),
      lineHeight: moderateHeight(1.85),
    },
    slipTitle: {
      color: colors.primary,
      fontSize: moderateHeight(1.55),
      lineHeight: moderateHeight(2.05),
      marginTop: moderateHeight(0.15),
    },
    slipSubtitle: {
      color: colors.gray,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.85),
      marginTop: moderateHeight(0.12),
    },
    chevron: {
      width: moderateWidth(4.8),
      height: moderateWidth(4.8),
      color: colors.primary,
    },
    emptyState: {
      minHeight: moderateHeight(34),
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(7),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    emptyTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(2),
    },
    emptyText: {
      color: colors.gray,
      fontSize: moderateHeight(1.38),
      lineHeight: moderateHeight(1.95),
      marginTop: moderateHeight(0.6),
    },
    addButton: {
      position: 'absolute',
      right: moderateWidth(5.2),
      bottom: moderateHeight(2.2),
      width: moderateHeight(6.6),
      height: moderateHeight(6.6),
      borderRadius: moderateHeight(3.3),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      elevation: 8,
      shadowRadius: 10,
      shadowOpacity: 0.22,
      shadowColor: colors.primaryDark,
      shadowOffset: { width: 0, height: 5 },
    },
    activeAddButton: {
      backgroundColor: colors.primaryDark,
    },
    addButtonPressed: {
      opacity: 0.78,
    },
    addIcon: {
      width: moderateHeight(3.4),
      height: moderateHeight(3.4),
      color: colors.white,
    },
    addMenu: {
      position: 'absolute',
      zIndex: 6,
      right: moderateWidth(5.2),
      bottom: moderateHeight(9.7),
      width: moderateWidth(48),
      overflow: 'visible',
      paddingVertical: moderateHeight(0.7),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 8,
      shadowRadius: 10,
      shadowOpacity: 0.18,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 5 },
    },
    addMenuArrow: {
      position: 'absolute',
      right: moderateWidth(5.1),
      bottom: moderateHeight(-0.75),
      width: moderateHeight(1.5),
      height: moderateHeight(1.5),
      transform: [{ rotate: '45deg' }],
      backgroundColor: colors.white,
      borderRightWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    addMenuOption: {
      minHeight: moderateHeight(5.2),
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: moderateWidth(3),
    },
    addMenuOptionPressed: {
      opacity: 0.72,
    },
    addMenuIconShell: {
      width: moderateHeight(3.8),
      height: moderateHeight(3.8),
      borderRadius: moderateHeight(1.9),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
    },
    addMenuIcon: {
      width: moderateHeight(2.15),
      height: moderateHeight(2.15),
      color: colors.primary,
    },
    addMenuOptionText: {
      color: colors.secondary,
      fontSize: moderateHeight(1.42),
      marginLeft: moderateWidth(1.4),
    },
    detailContent: {
      paddingHorizontal: moderateWidth(4.7),
      paddingTop: moderateHeight(1.4),
      paddingBottom: moderateHeight(9),
      rowGap: moderateHeight(1.35),
    },
    detailHero: {
      minHeight: moderateHeight(10.6),
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: moderateHeight(1.35),
      paddingHorizontal: moderateWidth(3.6),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    detailHeroIcon: {
      width: moderateWidth(13),
      height: moderateWidth(13),
      borderRadius: moderateWidth(6.5),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    detailHeroGlyph: {
      width: moderateWidth(6),
      height: moderateWidth(6),
      color: colors.primary,
    },
    detailHeroBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3.2),
    },
    detailName: {
      color: colors.secondary,
      fontSize: moderateHeight(1.8),
      lineHeight: moderateHeight(2.35),
    },
    detailSubtitle: {
      color: colors.gray,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.9),
      marginTop: moderateHeight(0.25),
    },
    detailStatusPill: {
      alignSelf: 'flex-start',
      paddingVertical: moderateHeight(0.35),
      paddingHorizontal: moderateWidth(2.4),
      borderRadius: moderateWidth(5),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      marginTop: moderateHeight(0.8),
    },
    detailStatusText: {
      color: colors.primary,
      fontSize: moderateHeight(1.22),
      lineHeight: moderateHeight(1.7),
    },
    detailCard: {
      paddingHorizontal: moderateWidth(3.4),
      paddingTop: moderateHeight(1.55),
      paddingBottom: moderateHeight(0.5),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    detailSectionTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.65),
      lineHeight: moderateHeight(2.2),
      marginBottom: moderateHeight(0.5),
    },
    detailRow: {
      minHeight: moderateHeight(6.8),
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: moderateHeight(1),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    detailRowIcon: {
      width: moderateWidth(8),
      height: moderateWidth(8),
      borderRadius: moderateWidth(4),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      marginRight: moderateWidth(2.5),
    },
    detailIcon: {
      width: moderateWidth(4),
      height: moderateWidth(4),
      color: colors.primary,
    },
    detailRowBody: {
      flex: 1,
      minWidth: 0,
    },
    detailLabel: {
      color: colors.gray,
      fontSize: moderateHeight(1.22),
      lineHeight: moderateHeight(1.7),
    },
    detailValue: {
      color: colors.secondary,
      fontSize: moderateHeight(1.42),
      lineHeight: moderateHeight(1.95),
      marginTop: moderateHeight(0.2),
    },
    detailUpdateReferralButton: {
      height: moderateHeight(5.8),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(2.2),
      backgroundColor: colors.primary,
      shadowColor: colors.primaryDark,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.16,
      shadowRadius: 9,
      elevation: 3,
      marginTop: moderateHeight(0.2),
      marginBottom: moderateHeight(2),
    },
    detailUpdateReferralButtonPressed: {
      opacity: 0.76,
    },
    detailUpdateReferralText: {
      color: colors.white,
      fontSize: moderateHeight(1.55),
    },
    updateStatusModalOverlay: {
      flex: 1,
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(5),
      backgroundColor: colors.overlay,
    },
    updateStatusModalBackdrop: {
      ...StyleSheet.absoluteFill,
    },
    updateStatusModalCard: {
      overflow: 'hidden',
      borderRadius: moderateWidth(3.2),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 10,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 14,
    },
    updateStatusModalHeader: {
      minHeight: moderateHeight(6.2),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: moderateWidth(4.2),
      backgroundColor: colors.background,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    updateStatusModalTitle: {
      flex: 1,
      color: colors.secondary,
      fontSize: moderateHeight(1.6),
      lineHeight: moderateHeight(2.15),
    },
    updateStatusCloseButton: {
      width: moderateWidth(8),
      height: moderateWidth(8),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(4),
      marginLeft: moderateWidth(2),
    },
    updateStatusCloseIcon: {
      width: moderateWidth(4.8),
      height: moderateWidth(4.8),
      color: colors.gray,
    },
    updateStatusModalBody: {
      paddingHorizontal: moderateWidth(4.2),
      paddingTop: moderateHeight(2),
      paddingBottom: moderateHeight(1.6),
    },
    updateStatusFieldLabel: {
      color: colors.secondary,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.85),
      marginBottom: moderateHeight(0.8),
    },
    updateStatusSelect: {
      minHeight: moderateHeight(5.6),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: moderateWidth(3),
      borderRadius: moderateWidth(2),
      borderWidth: StyleSheet.hairlineWidth,
    },
    updateStatusSelectText: {
      flex: 1,
      fontSize: moderateHeight(1.42),
      lineHeight: moderateHeight(1.95),
      marginRight: moderateWidth(2),
    },
    updateStatusChevron: {
      width: moderateWidth(4.5),
      height: moderateWidth(4.5),
      color: colors.gray,
    },
    updateStatusOptionsList: {
      rowGap: moderateHeight(0.75),
      marginTop: moderateHeight(1),
      padding: moderateWidth(1.2),
      borderRadius: moderateWidth(2),
      backgroundColor: colors.background,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    updateStatusOption: {
      minHeight: moderateHeight(4.7),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: moderateWidth(3),
      borderRadius: moderateWidth(1.8),
      borderWidth: StyleSheet.hairlineWidth,
    },
    updateStatusOptionText: {
      flex: 1,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.85),
      marginRight: moderateWidth(2),
    },
    updateStatusCheckIcon: {
      width: moderateWidth(4),
      height: moderateWidth(4),
    },
    updateStatusAmountBlock: {
      marginTop: moderateHeight(1.7),
    },
    updateStatusInput: {
      height: moderateHeight(5.4),
      color: colors.text,
      fontSize: moderateHeight(1.42),
      paddingHorizontal: moderateWidth(3.2),
      paddingVertical: 0,
      borderRadius: moderateWidth(2),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    updateStatusPlaceholder: {
      color: colors.gray,
    },
    updateStatusActions: {
      minHeight: moderateHeight(7.6),
      flexDirection: 'row',
      justifyContent: 'flex-end',
      columnGap: moderateWidth(2.4),
      paddingHorizontal: moderateWidth(4.2),
      paddingVertical: moderateHeight(1.4),
      backgroundColor: colors.background,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    updateStatusCancelButton: {
      minWidth: moderateWidth(24),
      minHeight: moderateHeight(4.9),
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(3.4),
      borderRadius: moderateWidth(2),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    updateStatusSubmitButton: {
      minWidth: moderateWidth(32),
      minHeight: moderateHeight(4.9),
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(3.4),
      borderRadius: moderateWidth(2),
      backgroundColor: colors.primary,
    },
    updateStatusCancelText: {
      color: colors.secondary,
      fontSize: moderateHeight(1.38),
    },
    updateStatusSubmitText: {
      color: colors.white,
      fontSize: moderateHeight(1.38),
    },
    meetFormContent: {
      flexGrow: 1,
      paddingHorizontal: moderateWidth(4.7),
      paddingTop: moderateHeight(1.4),
      paddingBottom: moderateHeight(7),
      backgroundColor: colors.background,
    },
    meetMemberPicker: {
      flex: 1,
      backgroundColor: colors.background,
    },
    meetMemberTabs: {
      flexDirection: 'row',
      marginTop: moderateHeight(1),
      marginHorizontal: moderateWidth(4.7),
      padding: moderateWidth(0.8),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    meetMemberTab: {
      flex: 1,
      minHeight: moderateHeight(4.5),
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      borderRadius: moderateWidth(1.8),
    },
    meetMemberActiveTab: {
      backgroundColor: colors.primary,
    },
    meetMemberTabText: {
      color: colors.gray,
      fontSize: moderateHeight(1.25),
    },
    meetMemberTabTextWithClear: {
      paddingRight: moderateWidth(6),
    },
    meetMemberActiveTabText: {
      color: colors.white,
    },
    meetMemberTabClearButton: {
      position: 'absolute',
      right: moderateWidth(2),
      width: moderateWidth(6),
      height: moderateWidth(6),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(3),
    },
    meetMemberTabClearIcon: {
      width: moderateWidth(3.5),
      height: moderateWidth(3.5),
      color: colors.white,
    },
    meetFormHero: {
      minHeight: moderateHeight(9.6),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: moderateHeight(1.35),
      paddingVertical: moderateHeight(1.35),
      paddingHorizontal: moderateWidth(3.6),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    meetFormHeroIcon: {
      width: moderateWidth(12),
      height: moderateWidth(12),
      borderRadius: moderateWidth(6),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    meetFormHeroGlyph: {
      width: moderateWidth(5.8),
      height: moderateWidth(5.8),
      color: colors.primary,
    },
    meetFormHeroBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3.2),
    },
    meetFormHeroTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.82),
      lineHeight: moderateHeight(2.35),
    },
    meetFormHeroSubtitle: {
      color: colors.gray,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.9),
      marginTop: moderateHeight(0.25),
    },
    meetSelectedMemberCard: {
      minHeight: moderateHeight(9.6),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: moderateHeight(1.35),
      paddingVertical: moderateHeight(1.35),
      paddingHorizontal: moderateWidth(3.4),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    meetSelectedMemberIcon: {
      width: moderateWidth(12),
      height: moderateWidth(12),
      borderRadius: moderateWidth(6),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    meetSelectedMemberGlyph: {
      width: moderateWidth(5.6),
      height: moderateWidth(5.6),
      color: colors.primary,
    },
    meetSelectedMemberBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3.2),
    },
    meetSelectedMemberName: {
      color: colors.secondary,
      fontSize: moderateHeight(1.65),
      lineHeight: moderateHeight(2.15),
      textTransform: 'capitalize',
    },
    meetSelectedMemberMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: moderateHeight(0.45),
    },
    meetSelectedMemberMetaIcon: {
      width: moderateWidth(3.6),
      height: moderateWidth(3.6),
      color: colors.gray,
    },
    meetSelectedMemberMeta: {
      flex: 1,
      color: colors.gray,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.85),
      marginLeft: moderateWidth(1.3),
    },
    meetChangeMemberButton: {
      width: moderateWidth(9.2),
      height: moderateWidth(9.2),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(4.6),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      marginLeft: moderateWidth(2),
    },
    meetChangeMemberIcon: {
      width: moderateWidth(4.6),
      height: moderateWidth(4.6),
      color: colors.primary,
    },
    meetFormSectionCard: {
      paddingTop: moderateHeight(1.55),
      paddingBottom: moderateHeight(0.35),
      paddingHorizontal: moderateWidth(3.4),
      marginBottom: moderateHeight(1.35),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    meetFormSectionHeader: {
      minHeight: moderateHeight(2.4),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: moderateHeight(1.15),
    },
    meetFormSectionTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.55),
    },
    meetFormSectionMeta: {
      color: colors.primary,
      fontSize: moderateHeight(1.2),
    },
    meetFormInputWrapper: {
      height: moderateHeight(5.7),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      borderRadius: moderateWidth(2),
      paddingLeft: moderateWidth(3.2),
      paddingRight: moderateWidth(2.8),
      backgroundColor: colors.primarySurface,
    },
    meetFormInputText: {
      color: colors.text,
      fontSize: moderateHeight(1.48),
      height: moderateHeight(5.4),
    },
    meetFormSelectText: {
      color: colors.text,
      fontSize: moderateHeight(1.48),
      lineHeight: moderateHeight(2.1),
    },
    meetFormDropdownWrapper: {
      flex: 0,
      marginTop: 0,
      marginBottom: moderateHeight(2),
    },
    meetFormIconBubble: {
      width: moderateWidth(7.2),
      height: moderateWidth(7.2),
      borderRadius: moderateWidth(3.6),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    meetFormFieldIcon: {
      width: moderateWidth(4),
      height: moderateWidth(4),
      color: colors.primary,
    },
    meetFormDropdownIcon: {
      width: moderateWidth(4.8),
      height: moderateWidth(4.8),
      color: colors.primary,
    },
    meetFormTextAreaWrapper: {
      minHeight: moderateHeight(10.4),
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingTop: moderateHeight(1.05),
      paddingLeft: moderateWidth(3.2),
      paddingRight: moderateWidth(2.8),
      marginBottom: moderateHeight(2),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      borderRadius: moderateWidth(2),
      backgroundColor: colors.primarySurface,
    },
    meetFormTextArea: {
      flex: 1,
      minHeight: moderateHeight(8.4),
      color: colors.text,
      fontSize: moderateHeight(1.48),
      lineHeight: moderateHeight(2.05),
      paddingTop: moderateHeight(0.55),
      paddingBottom: moderateHeight(0.8),
      paddingLeft: moderateWidth(2.1),
      paddingRight: 0,
    },
    referralPhoneWrapper: {
      height: moderateHeight(5.7),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: moderateHeight(2),
      paddingLeft: moderateWidth(3.2),
      paddingRight: moderateWidth(2.8),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      borderRadius: moderateWidth(2),
      backgroundColor: colors.primarySurface,
    },
    referralPhonePrefixInline: {
      height: moderateHeight(3.5),
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(2),
      marginLeft: moderateWidth(2),
      borderLeftWidth: StyleSheet.hairlineWidth,
      borderLeftColor: colors.primaryBorder,
    },
    referralPhonePrefixInlineText: {
      color: colors.primary,
      fontSize: moderateHeight(1.42),
    },
    referralPhoneInput: {
      flex: 1,
      height: '100%',
      color: colors.text,
      fontSize: moderateHeight(1.48),
      paddingLeft: moderateWidth(0.5),
      paddingRight: 0,
      paddingVertical: 0,
    },
    closeBusinessAmountInput: {
      flex: 1,
      height: '100%',
      color: colors.text,
      fontSize: moderateHeight(1.48),
      paddingLeft: moderateWidth(2.1),
      paddingRight: 0,
      paddingVertical: 0,
    },
    referralPhoneIcon: {
      width: moderateWidth(4.3),
      height: moderateWidth(4.3),
      color: colors.primary,
    },
    referralErrorText: {
      color: colors.brandRed,
      fontSize: moderateHeight(1.15),
      lineHeight: moderateHeight(1.65),
      marginTop: moderateHeight(-1.4),
      marginBottom: moderateHeight(1.4),
      marginLeft: moderateWidth(0.6),
    },
    referralTemperatureCard: {
      marginBottom: moderateHeight(2),
      paddingVertical: moderateHeight(1.35),
      paddingHorizontal: moderateWidth(3),
      borderRadius: moderateWidth(2.2),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    referralTemperatureHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: moderateHeight(1.2),
    },
    referralTemperatureTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(1.95),
    },
    referralTemperatureSubtitle: {
      color: colors.gray,
      fontSize: moderateHeight(1.16),
      lineHeight: moderateHeight(1.6),
      marginTop: moderateHeight(0.15),
    },
    referralTemperatureIcon: {
      width: moderateWidth(9),
      height: moderateWidth(9),
      borderRadius: moderateWidth(4.5),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.toastWarn,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    referralTemperatureGlyph: {
      width: moderateWidth(4.5),
      height: moderateWidth(4.5),
      color: '#F59E0B',
    },
    referralStarRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      columnGap: moderateWidth(1.5),
    },
    referralStarButton: {
      flex: 1,
      minHeight: moderateHeight(5),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(2),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    referralStarButtonActive: {
      backgroundColor: colors.toastWarn,
      borderColor: '#F59E0B',
    },
    referralStarIcon: {
      width: moderateWidth(5.1),
      height: moderateWidth(5.1),
      color: colors.gray,
    },
    referralStarIconActive: {
      color: '#F59E0B',
    },
    referralTemperatureResult: {
      minHeight: moderateHeight(5.8),
      justifyContent: 'center',
      marginTop: moderateHeight(1.2),
      paddingVertical: moderateHeight(0.85),
      paddingHorizontal: moderateWidth(3),
      borderRadius: moderateWidth(2),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    referralTemperatureResultTitle: {
      color: colors.primary,
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(1.95),
    },
    referralTemperatureResultText: {
      color: colors.gray,
      fontSize: moderateHeight(1.18),
      lineHeight: moderateHeight(1.65),
      marginTop: moderateHeight(0.15),
    },
    meetFormNotifyRow: {
      minHeight: moderateHeight(7.1),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: moderateHeight(1.35),
      paddingVertical: moderateHeight(1.15),
      paddingHorizontal: moderateWidth(3.4),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    meetFormCheckbox: {
      width: moderateWidth(5.6),
      height: moderateWidth(5.6),
      borderRadius: moderateWidth(1.3),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    meetFormCheckboxChecked: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    meetFormCheckboxIcon: {
      width: moderateWidth(3.8),
      height: moderateWidth(3.8),
      color: colors.white,
    },
    meetFormNotifyIcon: {
      width: moderateWidth(4.4),
      height: moderateWidth(4.4),
      color: colors.primary,
      marginLeft: moderateWidth(2.3),
    },
    meetFormNotifyBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(2),
    },
    meetFormNotifyTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.42),
      lineHeight: moderateHeight(1.95),
    },
    meetFormNotifyMeta: {
      color: colors.gray,
      fontSize: moderateHeight(1.22),
      lineHeight: moderateHeight(1.7),
      marginTop: moderateHeight(0.2),
    },
    meetFormActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      columnGap: moderateWidth(2.6),
      paddingTop: moderateHeight(0.2),
      paddingBottom: moderateHeight(1.8),
    },
    meetFormCancelButton: {
      flex: 0.82,
      height: moderateHeight(5.8),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(2.2),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    meetFormSubmitButton: {
      flex: 1.28,
      height: moderateHeight(5.8),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(2.2),
      backgroundColor: colors.primary,
      shadowColor: colors.primaryDark,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.16,
      shadowRadius: 9,
      elevation: 3,
    },
    meetFormDisabledButton: {
      opacity: 0.55,
    },
    meetFormControlPressed: {
      opacity: 0.76,
    },
    meetFormActionIcon: {
      width: moderateWidth(4.4),
      height: moderateWidth(4.4),
    },
    meetFormCancelText: {
      color: colors.secondary,
      fontSize: moderateHeight(1.45),
      marginLeft: moderateWidth(1.1),
    },
    meetFormSubmitText: {
      color: colors.white,
      fontSize: moderateHeight(1.45),
      marginLeft: moderateWidth(1.1),
    },
    meetFormStatusPill: {
      alignSelf: 'center',
      minHeight: moderateHeight(3.6),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: moderateHeight(0.55),
      paddingHorizontal: moderateWidth(3.2),
      borderRadius: moderateWidth(5),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      marginTop: moderateHeight(1.4),
    },
    meetFormStatusIcon: {
      width: moderateWidth(3.6),
      height: moderateWidth(3.6),
      color: colors.primary,
    },
    meetFormStatusText: {
      color: colors.primary,
      fontSize: moderateHeight(1.25),
      lineHeight: moderateHeight(1.75),
      marginLeft: moderateWidth(1),
    },
    formPlaceholder: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(7),
      backgroundColor: colors.background,
    },
    formPlaceholderIconShell: {
      width: moderateHeight(8.4),
      height: moderateHeight(8.4),
      borderRadius: moderateHeight(4.2),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    formPlaceholderIcon: {
      width: moderateHeight(4.2),
      height: moderateHeight(4.2),
      color: colors.primary,
    },
    formTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(2.3),
      lineHeight: moderateHeight(3),
      marginTop: moderateHeight(1.8),
    },
    formDescription: {
      color: colors.gray,
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(2.05),
      marginTop: moderateHeight(0.6),
    },
    formBackButton: {
      minHeight: moderateHeight(5),
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(6),
      borderRadius: moderateWidth(2),
      backgroundColor: colors.primary,
      marginTop: moderateHeight(2.4),
    },
    formBackButtonPressed: {
      opacity: 0.78,
    },
    formBackText: {
      color: colors.white,
      fontSize: moderateHeight(1.45),
    },
  });
};

export default useStyles;
