import { StyleSheet } from 'react-native';
import { useTheme } from '@react-navigation/native';
import { useDeviceDimensions } from '@hooks/useDeviceDimensions';

const useStyles = () => {
  const { colors } = useTheme();
  const { moderateWidth, moderateHeight } = useDeviceDimensions();

  return StyleSheet.create({
    header: {
      minHeight: moderateHeight(6.3),
      paddingVertical: moderateHeight(1),
      paddingHorizontal: moderateWidth(4),
      backgroundColor: colors.primary,
    },
    headerTitle: {
      color: colors.white,
      fontSize: moderateHeight(2.1),
      textTransform: 'none',
    },
    content: {
      paddingHorizontal: 0,
      backgroundColor: colors.background,
    },
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    topControls: {
      zIndex: 5,
      flexDirection: 'row',
      alignItems: 'center',
      paddingTop: moderateHeight(1),
      paddingHorizontal: moderateWidth(4.7),
    },
    tabs: {
      flex: 1,
      flexDirection: 'row',
      padding: moderateWidth(0.8),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    tab: {
      flex: 1,
      minHeight: moderateHeight(4.5),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(1.8),
    },
    activeTab: {
      backgroundColor: colors.primary,
    },
    tabText: {
      color: colors.gray,
      fontSize: moderateHeight(1.35),
    },
    activeTabText: {
      color: colors.white,
    },
    filterButton: {
      width: moderateHeight(5.4),
      height: moderateHeight(5.4),
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: moderateWidth(2),
      borderRadius: moderateWidth(2),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    activeFilterButton: {
      backgroundColor: colors.primary,
    },
    filterButtonPressed: {
      opacity: 0.72,
    },
    filterIcon: {
      width: moderateWidth(5),
      height: moderateWidth(5),
      color: colors.primary,
    },
    activeFilterIcon: {
      color: colors.white,
    },
    filterPopover: {
      position: 'absolute',
      top: moderateHeight(7.1),
      right: moderateWidth(4.7),
      width: moderateWidth(72),
      overflow: 'visible',
      padding: moderateWidth(3.2),
      borderRadius: moderateWidth(2.6),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 8,
      shadowRadius: 10,
      shadowOpacity: 0.18,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 5 },
    },
    filterPopoverArrow: {
      position: 'absolute',
      top: moderateHeight(-0.75),
      right: moderateWidth(4.5),
      width: moderateHeight(1.5),
      height: moderateHeight(1.5),
      transform: [{ rotate: '45deg' }],
      backgroundColor: colors.white,
      borderLeftWidth: StyleSheet.hairlineWidth,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    filterPopoverHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: moderateHeight(1.2),
    },
    filterTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.55),
    },
    clearFilterText: {
      color: colors.primary,
      fontSize: moderateHeight(1.35),
    },
    filterOptions: {
      rowGap: moderateHeight(1),
    },
    filterOption: {
      minHeight: moderateHeight(5.8),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      borderRadius: moderateWidth(2.2),
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
      paddingHorizontal: moderateWidth(3),
    },
    activeFilterOption: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    filterOptionPressed: {
      opacity: 0.72,
    },
    filterOptionIcon: {
      width: moderateWidth(4.7),
      height: moderateWidth(4.7),
      color: colors.primary,
    },
    filterOptionText: {
      flex: 1,
      color: colors.secondary,
      textAlign: 'left',
      fontSize: moderateHeight(1.35),
      marginLeft: moderateWidth(2.4),
    },
    activeFilterOptionText: {
      color: colors.white,
    },
    summaryCard: {
      marginTop: moderateHeight(1.35),
      marginHorizontal: moderateWidth(4.7),
      paddingVertical: moderateHeight(1.2),
      paddingHorizontal: moderateWidth(3.6),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    summaryTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(1.65),
      lineHeight: moderateHeight(2.15),
    },
    summarySubtitle: {
      color: colors.gray,
      fontSize: moderateHeight(1.28),
      lineHeight: moderateHeight(1.8),
      marginTop: moderateHeight(0.2),
    },
    listContent: {
      paddingHorizontal: moderateWidth(4.7),
      paddingTop: moderateHeight(1.25),
      paddingBottom: moderateHeight(13),
      rowGap: moderateHeight(1.1),
    },
    slipCard: {
      minHeight: moderateHeight(10.2),
      flexDirection: 'row',
      alignItems: 'center',
      overflow: 'hidden',
      position: 'relative',
      paddingVertical: moderateHeight(1.25),
      paddingHorizontal: moderateWidth(3.2),
      borderRadius: moderateWidth(2.3),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      elevation: 2,
      shadowRadius: 5,
      shadowOpacity: 0.08,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
    },
    slipCardPressed: {
      opacity: 0.72,
    },
    highlightBar: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      width: moderateWidth(1.3),
      backgroundColor: colors.toastSuccess,
    },
    slipIconShell: {
      width: moderateWidth(12),
      height: moderateWidth(12),
      borderRadius: moderateWidth(6),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primarySurface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.primaryBorder,
    },
    highlightedSlipIconShell: {
      backgroundColor: colors.toastSuccess,
      borderColor: colors.toastSuccess,
    },
    slipIcon: {
      width: moderateWidth(5.8),
      height: moderateWidth(5.8),
      color: colors.gray,
    },
    highlightedSlipIcon: {
      color: colors.primary,
    },
    slipBody: {
      flex: 1,
      minWidth: 0,
      marginLeft: moderateWidth(3.2),
    },
    slipDate: {
      color: colors.gray,
      fontSize: moderateHeight(1.38),
      lineHeight: moderateHeight(1.85),
    },
    slipTitle: {
      color: colors.primary,
      fontSize: moderateHeight(1.55),
      lineHeight: moderateHeight(2.05),
      marginTop: moderateHeight(0.15),
    },
    slipSubtitle: {
      color: colors.gray,
      fontSize: moderateHeight(1.35),
      lineHeight: moderateHeight(1.85),
      marginTop: moderateHeight(0.12),
    },
    chevron: {
      width: moderateWidth(4.8),
      height: moderateWidth(4.8),
      color: colors.primary,
    },
    emptyState: {
      minHeight: moderateHeight(34),
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(7),
      borderRadius: moderateWidth(2.4),
      backgroundColor: colors.white,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    emptyTitle: {
      color: colors.secondary,
      fontSize: moderateHeight(2),
    },
    emptyText: {
      color: colors.gray,
      fontSize: moderateHeight(1.38),
      lineHeight: moderateHeight(1.95),
      marginTop: moderateHeight(0.6),
    },
    addButton: {
      position: 'absolute',
      right: moderateWidth(5.2),
      bottom: moderateHeight(2.2),
      width: moderateHeight(6.6),
      height: moderateHeight(6.6),
      borderRadius: moderateHeight(3.3),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      elevation: 8,
      shadowRadius: 10,
      shadowOpacity: 0.22,
      shadowColor: colors.primaryDark,
      shadowOffset: { width: 0, height: 5 },
    },
    addButtonPressed: {
      opacity: 0.78,
    },
    addIcon: {
      width: moderateHeight(3.4),
      height: moderateHeight(3.4),
      color: colors.white,
    },
  });
};

export default useStyles;
